### ISSUE TITLE
Web interface?

### ISSUE THREAD

**Issue by terrag42** [EvanStanford/cams#1]
Great project, I enjoyed learning about the math that goes into the code. I've got a 3D printer, rubber bands and a laser pointer, but no golang experience. Any hope of seeing a web interface that allowed users to draw a pattern and click submit, and return the two .stl files? Maybe instead of drawing a pattern, the user could upload a .csv file with coordinate data.

**Comment by EvanStanford** [comment]
That would be neat and is the only request I have heard many times since posting yesterday. If I was to do this I would probably make an endpoint on Aws Lambda via Cloudfront, possibly with a static website on S3 static hosting.

Unfortunately, I think the actual chance of me doing this is 20%. If I get time later, I'll look into doing this. I'll post back with any updates.

**Comment by bricekevin** [comment]
Make it 30% I've got $10 for you :)

**Comment by StripeyType** [comment]
If we port this to JS, you could even skip the Lambda, and just host it anywhere static content can go up (including S3)

**Comment by Bill25XMarib** [comment]
This web interface would be great!

**Comment by TylonHH** [comment]
# +1

**Comment by ValkA** [comment]
I've created a new fork with a web_interface branch
https://github.com/ValkA/cams/tree/web_interface
#5
